data = read.csv("data.csv")
names(data)
plot(data$Sub_metering_1, type='l',xaxt='n',xlab='',ylab='Energy sub metering')
lines(data$Sub_metering_2, type='l', col='red')
lines(data$Sub_metering_3, type='l', col='blue')
axis(1,c(0,2880/2,2880),c('Thu','Fri','Sat'))
legend("topright",c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),lty=c(1,1,1),col=c('black','red','blue'))
dev.copy(png,'plot3.png')
dev.off()
